# Generated by Django 3.1.5 on 2021-01-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210123_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonWorkingDay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
    ]
