# Generated by Django 3.1.5 on 2021-01-24 01:50

import bookings.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_auto_20210123_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.make')),
                ('vehicleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('plate', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Other', 'Other')], max_length=10, null=True)),
                ('year', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1920), bookings.models.max_value_current_year], verbose_name='year')),
                ('engine_type', models.CharField(choices=[('MANUAL', 'MANUAL'), ('AUTOMATIC', 'AUTOMATIC')], max_length=10, null=True)),
                ('transmission', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(10000)])),
                ('fuel', models.CharField(choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL'), ('GAS', 'GAS')], max_length=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.customer')),
                ('vehicleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.vehiclemodel')),
            ],
        ),
    ]
