# Generated by Django 3.1.5 on 2021-01-24 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20210124_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+(-[A-Z0-9]+)*$', 'Only numbers, uppercase letters and dashes allowed.')]),
        ),
    ]
